service: user-company
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

functions:
  createUser:
    handler: controller/handlers.createNewUser
    events:
      - httpApi:
          path: /users/create
          method: post
  getAllUser:
    handler: controller/handlers.getAllUsers
    events:
      - httpApi:
          path: /users/all
          method: get
  getPagination:
    handler: controller/handlers.getFilter
    events:
      - httpApi:
          path: /users/filter
          method: get
  getUser:
    handler: controller/handlers.getSingleUser
    events:
      - httpApi:
          path:  /users/find/{user_id}
          method: get
  updateUser:
    handler: controller/handlers.updateUserData
    events:
      - httpApi:
          path:  /users/update/{user_id}
          method: patch
  deleteUser:
    handler: controller/handlers.deleteUser
    events:
      - httpApi:
          path:  /users/delete/{user_id}
          method: delete
  createCompany:
    handler: controller/cmphandlers.createNewCompany
    events:
      - httpApi:
          path: /company/create
          method: post
  getAllCompany:
    handler: controller/cmphandlers.getAllCompany
    events:
      - httpApi:
          path: /company/all
          method: get
  getCompany:
    handler: controller/cmphandlers.getSingleCompany
    events:
      - httpApi:
          path:  /company/find/{cmp_id}
          method: get
  updateCompany:
    handler: controller/cmphandlers.updateCmpData
    events:
      - httpApi:
          path:  /company/update/{cmp_id}
          method: patch
  deleteCompany:
    handler: controller/cmphandlers.deleteCompany
    events:
      - httpApi:
          path:  /company/delete/{cmp_id}
          method: delete
  usersInCompany:
    handler: controller/cmphandlers.usersInCompany
    events:
      - httpApi:
          path:  /users_in_company/{cmp_id}
          method: get
  companyOfUser:
    handler: controller/cmphandlers.companyOfUser
    events:
      - httpApi:
          path:  /company_of_user/{user_id}
          method: get